server:
  servlet:
    context-path: /demo2
# 日志配置，也可使用java配置的方式为feign配置日志
#feign:
 # client:
  #  config:
   #   spring-cloud-demo1:
    #    loggerLevel: full

logging:
  level:
    com.hwx.demo.feign.*: debug
# feign 使用OKHttp 连接池
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
